FirstResponseApp/Controllers/DumyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using FirstResponseApp.Data;
using FirstResponseApp.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FirstResponseApp.Controllers
{
    public class DumyController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public DumyController(ApplicationDbContext applicationDbContext)
        {
            this._applicationDbContext = applicationDbContext;
        }
        public IActionResult Index()
        {

            // var t = _applicationDbContext.TbUsers.FromSqlInterpolated($"GetList s").ToList();

            Matter obj = new Matter();
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem { Text = "Linfox First Response", Value = "1" });
            list.Add(new SelectListItem { Text = "Linfox Reports Following Examination", Value = "2" });
            list.Add(new SelectListItem { Text = "Linfox Rehabilitation Reviews/ Examinations", Value = "3" });
            list.Add(new SelectListItem { Text = "Linfox Reviews On The Papers (No Exam)", Value = "4" });
            list.Add(new SelectListItem { Text = "Linfox Follow Up", Value = "5" });
            list.Add(new SelectListItem { Text = "First Response Calendar", Value = "6" });
            list.Add(new SelectListItem { Text = "Armaguard", Value = "7" });
            list.Add(new SelectListItem { Text = "Armaguard First Response", Value = "8" });
            list.Add(new SelectListItem { Text = "Armaguard Report Following Examinations", Value = "9" });
            list.Add(new SelectListItem { Text = "Armaguard Reviews On The Paper (No Exam)", Value = "10" });
            list.Add(new SelectListItem { Text = "Armaguard Rehabilitation Reviews/ Examinations", Value = "11" });
            list.Add(new SelectListItem { Text = "Armaguard Follow Up", Value = "12" });
            list.Add(new SelectListItem { Text = "Linfox", Value = "13" });

            List<SelectListItem> listOrg = new List<SelectListItem>();
            listOrg.Add(new SelectListItem { Text = "Linfox", Value = "1" });
            listOrg.Add(new SelectListItem { Text = "HWLE", Value = "2" });
            listOrg.Add(new SelectListItem { Text = "Midlaw", Value = "3" });
            obj.ChannelList = list;
            obj.WaitingOnList = listOrg;

            string tem11 = generatePassword(7);

            return View(obj);
        }


        public string generatePassword(int length)
        {
            string validChars = "ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*?_-";
            Random random = new Random();

            // Select one random character at a time from the string  
            // and create an array of chars  
            char[] chars = new char[length];
            for (int i = 0; i < length; i++)
            {
                chars[i] = validChars[random.Next(0, validChars.Length)];
            }
            return new string(chars);
        }


        public IActionResult SendMail()
        {
            var mailingList = new List<string>()
            {
                "shelendra.vishwakarma@systematixindia.com",
                "darpan.chaturvedi@systematixindia.com",
                "puneet.shinde@systematixindia.com",
                "akhilesh.upadhyay@systematixindia.com",
                "nimish.tiwari@systematixindia.com",
                "nitesh.tiwari@systematixindia.com",
                "ankita.shrivastava@systematixindia.com"
            };

            string subject = "Salary Increment ";
            string body = "Dear Employee,<br /><br />Your work parformance is too good last 1 month. Managment decied to give party. you can go for party with your family and Reimbursement bill upto 5000 <br /><br />Thanks.";

            Parallel.ForEach(mailingList, row =>
            {
                SendEmail(row, subject, body);
            });

            return View();
        }

        public IActionResult AddNewUser()
        {
            User obj = new User();
            List<SelectListItem> listOrg = new List<SelectListItem>();
            listOrg.Add(new SelectListItem { Text = "Linfox", Value = "1" });
            listOrg.Add(new SelectListItem { Text = "HWLE", Value = "2" });
            listOrg.Add(new SelectListItem { Text = "Midlaw", Value = "3" });

            obj.OrganizetionList = listOrg;
            return View(obj);
        }


        private bool SendEmail(string recipient, string subject, string body)
        {
            MailMessage mm = new MailMessage("shelendra.vishwakarma@gmail.com", recipient);
            mm.Subject = subject;
            mm.Body = body;
            mm.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.EnableSsl = true;
            NetworkCredential NetworkCred = new NetworkCredential();
            NetworkCred.UserName = "siplInboundio@gmail.com";
            NetworkCred.Password = "Sipl@1234";
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = NetworkCred;
            smtp.Port = 587;
            smtp.Send(mm);
            return true;
        }


        [Obsolete]
        public async Task<JsonResult> GetApplicationData(string FilterSearch)
        {
            List<AddList> Model = new List<AddList>();
            try
            {
                FilterSearch = string.IsNullOrEmpty(FilterSearch) ? "" : FilterSearch;


                for (int i = 0; i <= 10; i++)
                {
                    AddList obj = new AddList();
                    obj.Id = i;
                    obj.Name = "test";
                    obj.Channel = "channel";
                    obj.WaitingOn = "waiting";
                    obj.AddedBy = "AddedBy";
                    obj.AddedOn = "AddedOn";
                    Model.Add(obj);
                }

            }
            catch (Exception ex)
            {

            }
            return Json(new { recordsFiltered = Model.Count(), recordsTotal = Model.Count(), data = Model });

        }

        public IActionResult CreateMatter()
        {
            Matter obj = new Matter();
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem { Text = "name", Value = "1" });
            List<SelectListItem> listOrg = new List<SelectListItem>();
            listOrg.Add(new SelectListItem { Text = "Linfox", Value = "1" });
            listOrg.Add(new SelectListItem { Text = "HWLE", Value = "2" });
            listOrg.Add(new SelectListItem { Text = "Midlaw", Value = "3" });

            List<SelectListItem> listUrs = new List<SelectListItem>();
            listUrs.Add(new SelectListItem { Text = "Barry", Value = "1" });
            listUrs.Add(new SelectListItem { Text = "John", Value = "2" });
            listUrs.Add(new SelectListItem { Text = "Stan", Value = "3" });
            obj.ChannelList = list;
            obj.WaitingOnList = listOrg;
            obj.UserNameList = listUrs;
            return View(obj);
        }

        public IActionResult TicketDetail()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }
        public IActionResult AddNewTicket()
        {
            Matter obj = new Matter();
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem { Text = "Linfox First Response", Value = "1" });
            list.Add(new SelectListItem { Text = "Linfox Reports Following Examination", Value = "2" });
            list.Add(new SelectListItem { Text = "Linfox Rehabilitation Reviews/ Examinations", Value = "3" });
            list.Add(new SelectListItem { Text = "Linfox Reviews On The Papers (No Exam)", Value = "4" });
            list.Add(new SelectListItem { Text = "Linfox Follow Up", Value = "5" });
            list.Add(new SelectListItem { Text = "First Response Calendar", Value = "6" });
            list.Add(new SelectListItem { Text = "Armaguard", Value = "7" });
            list.Add(new SelectListItem { Text = "Armaguard First Response", Value = "8" });
            list.Add(new SelectListItem { Text = "Armaguard Report Following Examinations", Value = "9" });
            list.Add(new SelectListItem { Text = "Armaguard Reviews On The Paper (No Exam)", Value = "10" });
            list.Add(new SelectListItem { Text = "Armaguard Rehabilitation Reviews/ Examinations", Value = "11" });
            list.Add(new SelectListItem { Text = "Armaguard Follow Up", Value = "12" });
            list.Add(new SelectListItem { Text = "Linfox", Value = "13" });

            List<SelectListItem> listOrg = new List<SelectListItem>();
            listOrg.Add(new SelectListItem { Text = "Linfox", Value = "1" });
            listOrg.Add(new SelectListItem { Text = "HWLE", Value = "2" });
            listOrg.Add(new SelectListItem { Text = "Midlaw", Value = "3" });

            List<SelectListItem> listUrs = new List<SelectListItem>();
            listUrs.Add(new SelectListItem { Text = "Barry", Value = "1" });
            listUrs.Add(new SelectListItem { Text = "John", Value = "2" });
            listUrs.Add(new SelectListItem { Text = "Stan", Value = "3" });
            obj.ChannelList = list;
            obj.WaitingOnList = listOrg;
            obj.UserNameList = listUrs;
            obj.TicketList = listUrs;
            return View(obj);
        }

        public IActionResult User()
        {
            User obj = new User();
            List<SelectListItem> listOrg = new List<SelectListItem>();
            listOrg.Add(new SelectListItem { Text = "Linfox", Value = "1" });
            listOrg.Add(new SelectListItem { Text = "HWLE", Value = "2" });

FirstResponseApp/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager;
@inject UserManager<ApplicationUser> UserManager;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">

    <link href="~/global_assets/css/icons/fontawesome/styles.min.css" rel="stylesheet" />
    <link href="~/global_assets/css/icons/icomoon/styles.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap_limitless.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/assets/css/layout.min.css" rel="stylesheet" />
    <link href="~/assets/css/components.min.css" rel="stylesheet" />

    <link href="~/assets/css/colors.min.css" rel="stylesheet" />


    <script src="~/global_assets/js/core/libraries/jquery.min.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.js"></script>
    <script src="~/global_assets/js/core/libraries/bootstrap.bundle.min.js"></script>
    <script src="~/global_assets/js/plugins/loaders/blockui.min.js"></script>

    <!-- /core JS files -->
    <!-- Theme JS files -->
    <script src="~/global_assets/js/plugins/visualization/d3/d3.min.js"></script>
    <script src="~/global_assets/js/plugins/visualization/d3/d3_tooltip.js"></script>
    <script src="~/global_assets/js/plugins/forms/styling/switchery.min.js"></script>
    <script src="~/global_assets/js/plugins/forms/styling/switchery.min.js"></script>
    <script src="~/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js"></script>
    <script src="~/global_assets/js/plugins/ui/moment/moment.min.js"></script>
    <script src="~/global_assets/js/plugins/pickers/daterangepicker.js"></script>
    @*<script src="~/global_assets/js/demo_pages/dashboard.js"></script>*@
    <script src="~/global_assets/js/demo_pages/form_layouts.js"></script>
    @*<script src="~/assets/js/app.js"></script>*@
    <script src="~/global_assets/js/demo_pages/datatables_basic.js"></script>

    <script src="~/global_assets/js/plugins/tables/datatables/datatables.min.js"></script>
    <script src="~/global_assets/js/plugins/forms/selects/select2.min.js"></script>
    <script src="~/global_assets/js/plugins/forms/selects/bootstrap_select.min.js"></script>
    <script src="~/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js"></script>
    <script src="~/global_assets/js/demo_pages/picker_date.js"></script>
    <script src="~/global_assets/js/plugins/uploaders/dropzone.min.js"></script>
    <script src="~/global_assets/js/demo_pages/uploader_dropzone.js"></script>
    <script src="~/global_assets/js/plugins/uploaders/fileinput/fileinput.min.js"></script>
    <script src="~/global_assets/js/demo_pages/uploader_bootstrap.js"></script>
    <script src="~/global_assets/js/plugins/forms/selects/form_select2.js"></script>
    <!-- Theme JS files -->
    @*<script src="~/global_assets/js/plugins/extensions/jquery_ui/interactions.min.js"></script>*@
    <script src="~/global_assets/js/plugins/extensions/jquery_ui/widgets.min.js"></script>
    <script src="~/global_assets/js/demo_pages/jqueryui_forms.js"></script>
    <script src="~/global_assets/js/plugins/notifications/sweet_alert.min.js"></script>
    <script src="~/global_assets/js/demo_pages/extra_sweetalert.js"></script>

    @*<link href="~/js/LayoutCss.min.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" />*@
    @*<script src="~/js/Bootstrap.min.js"></script>*@
    @*<script src="~/js/TableBundle.min.js"></script>
        <script src="~/js/javascriptsfiles.min.js"></script>
        <script src="~/js/site.js"></script>
        <script src="~/js/validate.min.js"></script>*@
</head>
<body class="sidebar-xs">



    <div id="loaderContainer" class="col-sm-12" style="display:none">

        <div class="loader"></div>
        @*<p style="text-align:center; font-weight:bold">Loading...</p>*@

    </div>


    <!-- Main navbar -->
    <div class="navbar navbar-expand-md navbar-dark">

        <div class="navbar-brand">


            <span class="d-inline-block text-decoration-none text-white">
                <img src="~/Images/Banner.jpg" style="height: 30px;" />


            </span>
        </div>

        <div class="d-md-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
                <i class="icon-tree5"></i>
            </button>
            <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
                <i class="icon-paragraph-justify3"></i>
            </button>
        </div>

        <div class="collapse navbar-collapse m-0" id="navbar-mobile">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                        <i class="icon-paragraph-justify3"></i>
                    </a>
                </li>
                <li class="nav-item d-flex align-items-center ml-2">
                    <h4 class="mb-0">First Response Ticket System</h4>
                </li>
            </ul>


            <partial name="_LoginPartial" />

        </div>
    </div>
    <!-- /main navbar -->
    <!-- Page content -->
    <div class="page-content">

        <!-- Main sidebar -->
        <div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

            <!-- Sidebar mobile toggler -->
            <div class="sidebar-mobile-toggler text-center">
                <a href="#" class="sidebar-mobile-main-toggle">
                    <i class="icon-arrow-left8"></i>
                </a>
                Navigation
                <a asp-action="Notifications" asp-controller="Dumy" class="sidebar-mobile-expand">
                    <i class="icon-screen-full"></i>
                    <i class="icon-screen-normal"></i>
                </a>
            </div>
            <!-- /sidebar mobile toggler -->
            <!-- Sidebar content -->
            <div class="sidebar-content">

                <!-- User menu -->
                @*<div class="sidebar-user">
                        <div class="card-body">
                            <div class="media">
                                <div class="mr-3">
                                    <a href="#"><img src="../../../../global_assets/images/placeholders/placeholder.jpg" width="38" height="38" class="rounded-circle" alt=""></a>
                                </div>

                                <div class="media-body">
                                    <div class="media-title font-weight-semibold">User Name</div>

                                </div>
                            </div>
                        </div>
                    </div>*@
                <!-- /user menu -->
                <!-- Main navigation -->
                <div class="card card-sidebar-mobile">
                    <ul id="divNav" class="nav nav-sidebar" data-nav-type="accordion">

                        <!-- Main -->

                        <li class="nav-item">
                            <a asp-controller="TicketUser" asp-action="Dashboard" asp-area="Ticket" class="nav-link" name="Primary" id="Dashboard">
                                <i class="icon-home4"></i>
                                <span>
                                    All Tickets
                                </span>
                            </a>
                        </li>

                        @{

                            var temSession = Newtonsoft.Json.JsonConvert.DeserializeObject<UserSessionDetail>(HttpContextAccessor.HttpContext.Session.GetString("UserSession"));


                        }

                        @if (temSession.OrganizationId.ToString().Trim() == "1")
                        {
                            <li class="nav-item">
                                <a asp-controller="TicketUser" asp-action="AllUser" asp-area="Ticket" class="nav-link" name="Primary" id="UserManagement">
                                    <span></span>
                                    <i class="icon-file-text3"></i>
                                    <span style="position:relative;">
                                        User Management
                                    </span>
                                </a>
                            </li>
                        }

                        @*<li class="nav-item">
                                <a asp-controller="Dumy" asp-action="Notifications" class="nav-link" name="Primary" id="Notification">
                                    <span></span>
                                    <i class="icon-file-text3"></i>
                                    <span style="position:relative;">
                                        Notification
                                    </span>
                                </a>
                            </li>*@
                        <li class="nav-item">
                            <a asp-controller="TicketUser" asp-action="Profile" class="nav-link" asp-area="Ticket" name="TicketUser" id="Profile">
                                <span></span>
                                <i class="fas fa-user-circle"></i>
                                <span style="position:relative;">
                                    Profile
                                </span>
                            </a>
                        </li>
                        @*<li class="nav-item">
                                <a asp-controller="PrimaryUser" asp-action="History" class="nav-link" name="Primary" id="History">
                                    <i class="icon-database-check"></i>
                                    <span>
                                        History
                                    </span>
                                </a>
                            </li>*@
                    </ul>
                </div>
                <!-- /main navigation -->

            </div>
            <!-- /sidebar content -->

        </div>
        <!-- /main sidebar -->
        <!-- Main content -->
        <div class="content-wrapper">
            <div>
                @RenderBody()
            </div>

            <!-- Footer -->
            @*<div class="navbar navbar-expand-lg navbar-light footer-section">
            <div class="text-center d-lg-none w-100">
                <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
                    <i class="icon-unfold mr-2"></i>
                    Footer
                </button>
            </div>

            <div class="navbar-collapse collapse m-0" id="navbar-footer">
                <span class="navbar-text">
                    &copy; @DateTime.Now.Year. <span>First Response Ticket System</span>
                </span>
            </div>
        </div>*@
            <div class="container-fluid footer-section">
                <footer class="p-3 border-top text-muted">

                    &copy; @DateTime.Now.Year.  - First Response Ticket System

                </footer>
            </div>

            <!-- /footer -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->
    <!-- /main navbar -->

    <div id="loaderContainer" class="col-sm-12" style="display:none">

        <div class="loader"></div>
        @*<p style="text-align:center; font-weight:bold">Loading...</p>*@

    </div>

    @RenderSection("Scripts", required: false)

    <script>

        $(function () {
            var current = location.pathname;
            $('#divNav li a').each(function () {
                var $this = $(this);
                //alert($this.attr('href'));
                // if the current path is like this link, make it active
                if ($this.attr('href').indexOf(current) !== -1) {
                    $this.parent().addClass('active');
                }
            })
        })

    </script>
    <script>
        $(document).ready(function () {
            $(".sidebar-main-toggle").click(function () {
                $('body').toggleClass('sidebar-xs');
            });
        });
    </script>


</body>

</html>

FirstResponseApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstResponseApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstResponseApp</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                   <!--<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>-->
        </div>
        </nav>
        </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FirstResponseApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>